/*
===========================================================================
Devotion menuDef header — Quake Live ownerdraw / show-flag dialect.

Team Arena numeric IDs differ; the TA header is preserved as menudef_ta.h.
Stock TA .menu files must be converted to these IDs before use.
===========================================================================
*/

#define ITEM_TYPE_TEXT 0
#define ITEM_TYPE_BUTTON 1
#define ITEM_TYPE_RADIOBUTTON 2
#define ITEM_TYPE_CHECKBOX 3
#define ITEM_TYPE_EDITFIELD 4
#define ITEM_TYPE_COMBO 5
#define ITEM_TYPE_LISTBOX 6
#define ITEM_TYPE_MODEL 7
#define ITEM_TYPE_OWNERDRAW 8
#define ITEM_TYPE_NUMERICFIELD 9
#define ITEM_TYPE_SLIDER 10
#define ITEM_TYPE_YESNO 11
#define ITEM_TYPE_MULTI 12
#define ITEM_TYPE_BIND 13
#define ITEM_TYPE_SLIDER_COLOR 14
#define ITEM_TYPE_PRESET 15
#define ITEM_TYPE_PRESETLIST 16

#define ITEM_ALIGN_LEFT 0
#define ITEM_ALIGN_CENTER 1
#define ITEM_ALIGN_RIGHT 2

#define WIDESCREEN_STRETCH 0
#define WIDESCREEN_LEFT 1
#define WIDESCREEN_CENTER 2
#define WIDESCREEN_RIGHT 3

#define FONT_DEFAULT 0
#define FONT_SANS 1
#define FONT_MONO 2

#define ITEM_TEXTSTYLE_NORMAL 0
#define ITEM_TEXTSTYLE_BLINK 1
#define ITEM_TEXTSTYLE_PULSE 2
#define ITEM_TEXTSTYLE_SHADOWED 3
#define ITEM_TEXTSTYLE_OUTLINED 4
#define ITEM_TEXTSTYLE_OUTLINESHADOWED 5
#define ITEM_TEXTSTYLE_SHADOWEDMORE 6

#define WINDOW_BORDER_NONE 0
#define WINDOW_BORDER_FULL 1
#define WINDOW_BORDER_HORZ 2
#define WINDOW_BORDER_VERT 3
#define WINDOW_BORDER_KCGRADIENT 4

#define WINDOW_STYLE_EMPTY 0
#define WINDOW_STYLE_FILLED 1
#define WINDOW_STYLE_GRADIENT 2
#define WINDOW_STYLE_SHADER 3
#define WINDOW_STYLE_TEAMCOLOR 4
#define WINDOW_STYLE_CINEMATIC 5

#define MENU_TRUE 1
#define MENU_FALSE 0

#define HUD_VERTICAL 0x00
#define HUD_HORIZONTAL 0x01

#define LISTBOX_TEXT 0x00
#define LISTBOX_IMAGE 0x01

#define FEEDER_HEADS 0x00
#define FEEDER_MAPS 0x01
#define FEEDER_SERVERS 0x02
#define FEEDER_CLANS 0x03
#define FEEDER_ALLMAPS 0x04
#define FEEDER_REDTEAM_LIST 0x05
#define FEEDER_BLUETEAM_LIST 0x06
#define FEEDER_PLAYER_LIST 0x07
#define FEEDER_TEAM_LIST 0x08
#define FEEDER_MODS 0x09
#define FEEDER_DEMOS 0x0a
#define FEEDER_SCOREBOARD 0x0b
#define FEEDER_Q3HEADS 0x0c
#define FEEDER_SERVERSTATUS 0x0d
#define FEEDER_FINDPLAYER 0x0e
#define FEEDER_CINEMATICS 0x0f
#define FEEDER_ENDSCOREBOARD 0x10
#define FEEDER_REDTEAM_STATS 0x11
#define FEEDER_BLUETEAM_STATS 0x12
#define FEEDER_CVMAPS 0x13

/* ownerdraw visibility flags (QL) */
#define CG_SHOW_BLUE_TEAM_HAS_REDFLAG 0x00000001
#define CG_SHOW_RED_TEAM_HAS_BLUEFLAG 0x00000002
#define CG_SHOW_DUEL 0x00000004
#define CG_SHOW_CLAN_ARENA 0x00000008
#define CG_SHOW_FFA CG_SHOW_CLAN_ARENA /* FFA-only boards (reuse unused CA bit) */
#define CG_SHOW_CTF 0x00000010
#define CG_SHOW_ONEFLAG 0x00000020
#define CG_SHOW_OBELISK 0x00000040
#define CG_SHOW_HARVESTER 0x00000080
#define CG_SHOW_DOMINATION 0x00000100
#define CG_SHOW_ANYNONTEAMGAME 0x00000200
#define CG_SHOW_ANYTEAMGAME 0x00000400
#define CG_SHOW_HEALTHCRITICAL 0x00000800
#define CG_SHOW_IF_NOT_WARMUP 0x00001000
#define CG_SHOW_IF_PLAYER_HAS_FLAG 0x00002000
#define CG_SHOW_IF_WARMUP 0x00004000
#define CG_SHOW_IF_BLUE_IS_FIRST_PLACE 0x00008000
#define CG_SHOW_TEAMINFO 0x00010000
#define CG_SHOW_NOTEAMINFO 0x00020000
#define CG_SHOW_OTHERTEAMHASFLAG 0x00040000
#define CG_SHOW_YOURTEAMHASENEMYFLAG 0x00080000
#define CG_SHOW_INTERMISSION 0x00100000
#define CG_SHOW_NOTINTERMISSION 0x00200000
#define CG_SHOW_IF_MSG_PRESENT 0x00400000
#define CG_SHOW_IF_NOTICE_PRESENT 0x00800000
#define CG_SHOW_IF_CHAT_VISIBLE 0x01000000
#define CG_SHOW_IF_PLYR_IS_FIRST_PLACE 0x02000000
#define CG_SHOW_IF_PLYR_IS_NOT_FIRST_PLACE 0x04000000
#define CG_SHOW_IF_RED_IS_FIRST_PLACE 0x08000000
#define CG_SHOW_2DONLY 0x10000000
#define CG_SHOW_IF_PLYR_IS_ON_RED 0x20000000
#define CG_SHOW_IF_PLYR_IS_ON_BLUE 0x40000000
#define CG_SHOW_PLAYERS_REMAINING 0x80000000

#define UI_SHOW_LEADER 0x00000001
#define UI_SHOW_NOTLEADER 0x00000002
#define UI_SHOW_FAVORITESERVERS 0x00000004
#define UI_SHOW_ANYNONTEAMGAME 0x00000008
#define UI_SHOW_ANYTEAMGAME 0x00000010
#define UI_SHOW_NEWHIGHSCORE 0x00000020
#define UI_SHOW_DEMOAVAILABLE 0x00000040
#define UI_SHOW_NEWBESTTIME 0x00000080
#define UI_SHOW_FFA 0x00000100
#define UI_SHOW_NOTFFA 0x00000200
#define UI_SHOW_NETANYNONTEAMGAME 0x00000400
#define UI_SHOW_NETANYTEAMGAME 0x00000800
#define UI_SHOW_NOTFAVORITESERVERS 0x00001000

/* QL cgame ownerdraws */
#define CG_SERVER_SETTINGS 1
#define CG_STARTING_WEAPONS 2
#define CG_GAME_LIMIT 3
#define CG_GAME_TYPE 4
#define CG_GAME_TYPE_ICON 5
#define CG_GAME_TYPE_MAP 6
#define CG_GAME_STATUS 7
#define CG_MATCH_DETAILS 8
#define CG_MATCH_END_CONDITION 9
#define CG_MATCH_STATUS 10
#define CG_CAPFRAGLIMIT 11
#define CG_LEVELTIMER 12
#define CG_ROUND 13
#define CG_ROUNDTIMER 14
#define CG_OVERTIME 15
#define CG_LOCALTIME 16
#define CG_PLAYER_COUNTS 17
#define CG_MAP_NAME 18
#define CG_PLAYER_HEAD 36
#define CG_PLAYERMODEL 37
#define CG_PLAYER_ARMOR_ICON 38
#define CG_PLAYER_ARMOR_ICON2D 39
#define CG_PLAYER_ARMOR_VALUE 40
#define CG_PLAYER_ARMOR_BAR_100 41
#define CG_PLAYER_ARMOR_BAR_200 42
#define CG_ARMORTIERED_COLORIZED 43
#define CG_PLAYER_HEALTH 44
#define CG_PLAYER_HEALTH_BAR_100 45
#define CG_PLAYER_HEALTH_BAR_200 46
#define CG_PLAYER_AMMO_ICON 47
#define CG_PLAYER_AMMO_ICON2D 48
#define CG_PLAYER_AMMO_VALUE 49
#define CG_PLAYER_ITEM 50
#define CG_PLAYER_SCORE 51
#define CG_RACE_STATUS 52
#define CG_RACE_TIMES 53
#define CG_ONEFLAG_STATUS 54
#define CG_PLAYER_HASFLAG 55
#define CG_PLAYER_HASFLAG2D 56
#define CG_HARVESTER_SKULLS 57
#define CG_HARVESTER_SKULLS2D 58
#define CG_PLAYER_HASKEY 59
#define CG_CTF_POWERUP 60
#define CG_AREA_POWERUP 61
#define CG_TEAM_COLOR 62
#define CG_KILLER 63
#define CG_ACCURACY 64
#define CG_ASSISTS 65
#define CG_CAPTURES 66
#define CG_COMBOKILLS 67
#define CG_DEFEND 68
#define CG_EXCELLENT 69
#define CG_GAUNTLET 70
#define CG_IMPRESSIVE 71
#define CG_PERFECT 74
#define CG_SPECTATORS 81
#define CG_MATCH_WINNER 82
#define CG_1STPLACE 83
#define CG_1ST_PLACE_SCORE 84
#define CG_2NDPLACE 86
#define CG_2ND_PLACE_SCORE 87
#define CG_PLAYER_OBIT 88
#define CG_AREA_NEW_CHAT 89
#define CG_FOLLOW_PLAYER_NAME 94
#define CG_FOLLOW_PLAYER_NAME_EX 95
#define CG_SPEEDOMETER 96
#define CG_WP_VERTICAL 97
#define CG_ACC_VERTICAL 98
#define CG_TEAM_COLORIZED 99
#define CG_TEAM_PLYR_COUNT 100
#define CG_ENEMY_PLYR_COUNT 101
#define CG_MINI_PLYR_SCORES 102 /* composite 1–2 player name/score callout */
#define CG_1ST_PLYR 103
#define CG_1ST_PLYR_SCORE 105
#define CG_2ND_PLYR 193
#define CG_2ND_PLYR_SCORE 195
#define CG_RED_FLAGSTATUS 283
#define CG_RED_SCORE 284
#define CG_RED_NAME 285
#define CG_RED_OWNED_FLAGS 286
#define CG_RED_CLAN_PLYRS 290
#define CG_BLUE_FLAGSTATUS 310
#define CG_BLUE_NAME 311
#define CG_BLUE_SCORE 312
#define CG_BLUE_OWNED_FLAGS 313
#define CG_BLUE_CLAN_PLYRS 317
#define CG_FLAG_STATUS 337
#define CG_HEALTH_COLORIZED 338
#define CG_MATCH_STATE 339

#define UI_OWNERDRAW_BASE 512
#define UI_HANDICAP 513
#define UI_PLAYERMODEL 514
#define UI_GAMETYPE 515
#define UI_CROSSHAIR 534
#define UI_NETGAMETYPE 537

/* Voice chat strings (shared with game/AI; unchanged from Team Arena) */
#define VOICECHAT_GETFLAG			"getflag"
#define VOICECHAT_OFFENSE			"offense"
#define VOICECHAT_DEFEND			"defend"
#define VOICECHAT_DEFENDFLAG		"defendflag"
#define VOICECHAT_PATROL			"patrol"
#define VOICECHAT_CAMP				"camp"
#define VOICECHAT_FOLLOWME			"followme"
#define VOICECHAT_RETURNFLAG		"returnflag"
#define VOICECHAT_FOLLOWFLAGCARRIER	"followflagcarrier"
#define VOICECHAT_YES				"yes"
#define VOICECHAT_NO				"no"
#define VOICECHAT_ONGETFLAG			"ongetflag"
#define VOICECHAT_ONOFFENSE			"onoffense"
#define VOICECHAT_ONDEFENSE			"ondefense"
#define VOICECHAT_ONPATROL			"onpatrol"
#define VOICECHAT_ONCAMPING			"oncamp"
#define VOICECHAT_ONFOLLOW			"onfollow"
#define VOICECHAT_ONFOLLOWCARRIER	"onfollowcarrier"
#define VOICECHAT_ONRETURNFLAG		"onreturnflag"
#define VOICECHAT_INPOSITION		"inposition"
#define VOICECHAT_IHAVEFLAG			"ihaveflag"
#define VOICECHAT_BASEATTACK		"baseattack"
#define VOICECHAT_ENEMYHASFLAG		"enemyhasflag"
#define VOICECHAT_STARTLEADER		"startleader"
#define VOICECHAT_STOPLEADER		"stopleader"
#define VOICECHAT_TRASH				"trash"
#define VOICECHAT_WHOISLEADER		"whoisleader"
#define VOICECHAT_WANTONDEFENSE		"wantondefense"
#define VOICECHAT_WANTONOFFENSE		"wantonoffense"
#define VOICECHAT_KILLINSULT		"kill_insult"
#define VOICECHAT_TAUNT				"taunt"
#define VOICECHAT_DEATHINSULT		"death_insult"
#define VOICECHAT_KILLGAUNTLET		"kill_gauntlet"
#define VOICECHAT_PRAISE			"praise"
