/*
===========================================================================
Generated by scripts/gen_cvar_descriptions.py — do not edit by hand.
===========================================================================
*/

#if !defined( BG_CVAR_DESC_H )
#define BG_CVAR_DESC_H

typedef struct {
	const char *name;
	const char *description;
} cvarDesc_t;

const char *BG_GameCvarDescription( const char *name );
const char *BG_CgameCvarDescription( const char *name );

void BG_RegisterGameCvarDescriptions( void );
void BG_RegisterCgameCvarDescriptions( void );

#endif
