#!/usr/bin/env python3
"""Generate bg_cvar_desc.c from docs/SERVER-CVARS.md and docs/CLIENT-CVARS.md."""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "ratoa_gamecode" / "code" / "game" / "bg_cvar_desc.c"
HEADER = ROOT / "ratoa_gamecode" / "code" / "game" / "bg_cvar_desc.h"

ROW_RE = re.compile(
    r"^\|\s*`([^`]+)`\s*\|[^|]+\|[^|]+\|[^|]+\|\s*(.+?)\s*\|\s*$"
)


def parse_table(path: Path) -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        m = ROW_RE.match(line)
        if not m:
            continue
        name, desc = m.group(1).strip(), m.group(2).strip()
        if name.lower() == "name":
            continue
        rows.append((name, desc))
    rows.sort(key=lambda item: item[0])
    return rows


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_table(name: str, rows: list[tuple[str, str]]) -> str:
    if not rows:
        return f"static const cvarDesc_t {name}[] = {{\n}};\n"
    lines = [f"static const cvarDesc_t {name}[] = {{"]
    for cvar_name, desc in rows:
        lines.append(f"\t{{ {c_string(cvar_name)}, {c_string(desc)} }},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> int:
    server_rows = parse_table(ROOT / "docs" / "SERVER-CVARS.md")
    client_rows = parse_table(ROOT / "docs" / "CLIENT-CVARS.md")

    source = f"""/*
===========================================================================
Generated by scripts/gen_cvar_descriptions.py — do not edit by hand.
===========================================================================
*/

#include "bg_cvar_desc.h"
#include "bg_trap_ext.h"

{emit_table("gameCvarDescriptions", server_rows)}
static const int gameCvarDescriptionCount = sizeof( gameCvarDescriptions ) / sizeof( gameCvarDescriptions[0] );

{emit_table("cgameCvarDescriptions", client_rows)}
static const int cgameCvarDescriptionCount = sizeof( cgameCvarDescriptions ) / sizeof( cgameCvarDescriptions[0] );

static const char *BG_LookupCvarDescription( const cvarDesc_t *table, int count, const char *name ) {{
\tint i;

\tif ( !name || !name[0] ) {{
\t\treturn NULL;
\t}}

\tfor ( i = 0; i < count; i++ ) {{
\t\tif ( !Q_stricmp( table[i].name, name ) ) {{
\t\t\treturn table[i].description;
\t\t}}
\t}}

\treturn NULL;
}}

const char *BG_GameCvarDescription( const char *name ) {{
\treturn BG_LookupCvarDescription( gameCvarDescriptions, gameCvarDescriptionCount, name );
}}

const char *BG_CgameCvarDescription( const char *name ) {{
\treturn BG_LookupCvarDescription( cgameCvarDescriptions, cgameCvarDescriptionCount, name );
}}

void BG_RegisterGameCvarDescriptions( void ) {{
\tint i;
\tconst char *desc;

\tBG_TrapExt_Init();

\tfor ( i = 0; i < gameCvarDescriptionCount; i++ ) {{
\t\tdesc = gameCvarDescriptions[i].description;
\t\tif ( desc && desc[0] ) {{
\t\t\tBG_RegisterCvarDescription( gameCvarDescriptions[i].name, desc );
\t\t}}
\t}}
}}

void BG_RegisterCgameCvarDescriptions( void ) {{
\tint i;
\tconst char *desc;

\tBG_TrapExt_Init();

\tfor ( i = 0; i < cgameCvarDescriptionCount; i++ ) {{
\t\tdesc = cgameCvarDescriptions[i].description;
\t\tif ( desc && desc[0] ) {{
\t\t\tBG_RegisterCvarDescription( cgameCvarDescriptions[i].name, desc );
\t\t}}
\t}}
}}
"""

    header = """/*
===========================================================================
Generated by scripts/gen_cvar_descriptions.py — do not edit by hand.
===========================================================================
*/

#if !defined( BG_CVAR_DESC_H )
#define BG_CVAR_DESC_H

typedef struct {
	const char *name;
	const char *description;
} cvarDesc_t;

const char *BG_GameCvarDescription( const char *name );
const char *BG_CgameCvarDescription( const char *name );

void BG_RegisterGameCvarDescriptions( void );
void BG_RegisterCgameCvarDescriptions( void );

#endif
"""

    OUT.write_text(source, encoding="utf-8", newline="\n")
    HEADER.write_text(header, encoding="utf-8", newline="\n")
    print(f"Wrote {len(server_rows)} server and {len(client_rows)} client cvar descriptions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
