name: Build
on: [push]

jobs:

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update
      run: |
        sudo apt-get update

    - name: Build QVM
      run: |
        make -j12
      env:
        ARCHIVE: 1

    - name: Set artifact name
      run: |
        git fetch --tags
        FILENAME_HERE=$(ls build/)
        GIT_DESCRIBECOMMIT=$(git describe --tags --always)
        ARTIFACT_NAME="${FILENAME_HERE%.*}-${GIT_DESCRIBECOMMIT##*-}"
        echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV

    - name: Store pk3 artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: |
          build/*.pk3
        if-no-files-found: error
        retention-days: 7

    - name: Publish a release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        files: |
          build/*.pk3
