name: Build
on: [push]

jobs:

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Update
      run: |
        sudo apt-get update

    - name: Get latest tag using git
      id: get_latest_tag
      run: echo "LATEST_TAG=$(git describe --tags --abbrev=0)"

    - name: Use tag from event trigger
      run: echo "The latest tag is ${{ github.ref_name }}"

    - name: Get latest tag using gh CLI
      id: get_latest_tag_2
      run: echo "LATEST_TAG=$(gh release view --json tagName -q '.tagName')"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build QVM
      run: |
        make
      env:
        ARCHIVE: 1

    - name: Set artifact name
      run: |
        git fetch --tags
        FILENAME_HERE=$(ls build/)
        ARTIFACT_NAME="${FILENAME_HERE%.*}"
        echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV

    - name: Store pk3 artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: |
          build/*.pk3
        if-no-files-found: error
        retention-days: 7

    - name: Publish a release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        files: |
          build/*.pk3
